In [4]:
import config
import ObservationOperator
import numpy as np

In [16]:
import tensorflow as tf
import MLOnline

In [17]:
from importlib import reload
reload(MLOnline)
reload(ObservationOperator)
tf.reset_default_graph()

In [18]:
H = ObservationOperator.MLObsVer1

In [23]:
H(np.array([[-200,0.75],]))

array([[1.4938071e+02, 2.8626963e-02, 1.4485379e+02, 7.7762871e+01,
        3.4559101e-02]], dtype=float32)

In [124]:
xinit = np.array([-200,0.75])
sigmainit = 0.9
xinit * (1 + np.clip(sigmainit * np.random.randn(*xinit.shape),-0.5,1))

array([-218.22216223,    0.49184304])

In [168]:
sigma = xinit * np.clip(sigmainit * np.random.randn(*xinit.shape),-0.5,1)

In [169]:
xinit + sigma

array([-384.09147514,    0.45655234])

In [171]:
reload(config)

<module 'config' from '/Users/siyangjing/Documents/GitHub/Data-Assimilation/FA18/Modularized/config.py'>

In [174]:
config.GetArray('TrueModel','value_bound_lower')

array([-9999.,     0.])

In [180]:
b = np.array([-0.5,-0.5,-0.5])
c = np.array([0.5,0.5,0.5])

In [196]:
A = np.random.randn(3,3)

In [197]:
np.clip(A,b,c)

array([[-0.032546  , -0.34533858,  0.4950122 ],
       [ 0.28127128, -0.43410561,  0.5       ],
       [ 0.13168557, -0.48243723,  0.35634058]])

In [199]:
np.arange()

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])